---
version: 2.1

docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth

orbs:
  slack: circleci/slack@3.4.2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: lint
          command: flake8

  check-wpscan:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Check WPScan API
          command: |
            output="$(./bin/scan.py --function wpscan)"
            echo "export OUTPUT=\"${output}\"" >> $BASH_ENV
            cat "$BASH_ENV"
      - slack/notify:
          channel: C02FB4CQWLF
          color: '#cb0e0e'
          message: "${OUTPUT}"
          include_job_number_field: false
          include_project_field: false
          include_visit_job_action: false

  check-composer:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Check composer updates
          command: |
            sudo mkdir -p /app/source/artifacts
            output="$(./bin/scan.py --function composer)"
            echo "export OUTPUT=\"${output}\"" >> $BASH_ENV
            cat "$BASH_ENV"
      - slack/notify:
          channel: C02FB4CQWLF
          color: '#cb0e0e'
          message: "${OUTPUT}"
          include_job_number_field: false
          include_project_field: false
          include_visit_job_action: false

workflows:
  branch:
    jobs:
      - lint

  composer:
    jobs:
      - check-wpscan:
          context: org-global
          filters:
            branches:
              only: composer
      - check-composer:
          context: org-global
          filters:
            branches:
              only: composer

  cron-check:
    triggers:
      - schedule:
          # Weekly 1000UTC Monday
          cron: "0 10 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - check-wpscan:
          context: org-global
      - check-composer:
          context: org-global
